package es.makigas.escuela.frames.profesores;

import es.makigas.escuela.dao.DAOException;
import es.makigas.escuela.dao.DAOManager;
import es.makigas.escuela.dao.mysql.MySQLDaoManager;
import es.makigas.escuela.modelo.Profesor;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class ListProfesoresFrame extends javax.swing.JFrame {

    private DAOManager manager;
    
    private ProfesoresTableModel modelo;
    
    public ListProfesoresFrame(DAOManager manager) throws DAOException {
        initComponents();
        this.manager = manager;
        this.modelo = new ProfesoresTableModel(manager.getProfesorDAO());
        this.tabla.setModel(modelo);
        actualizarTabla();
        tabla.getSelectionModel().addListSelectionListener(e -> {
            boolean valido = (tabla.getSelectedRow() != -1);
            edit.setEnabled(valido);
            borrar.setEnabled(valido);
        });
    }
    
    void actualizarTabla() throws DAOException {
        progreso.setText("Actualizando datos...");
        modelo.updateModel();
        modelo.fireTableDataChanged();
        progreso.setText(modelo.getRowCount() + " profesores visibles.");
    }
    
    Profesor obtenerProfesor() throws DAOException {
        Long id = (Long) modelo.getValueAt(tabla.getSelectedRow(), 0);
        return manager.getProfesorDAO().obtener(id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        add = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        edit = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        guardar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        progreso = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        detalle = new es.makigas.escuela.frames.profesores.DetalleProfesorPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de profesores");

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        add.setText("Nuevo");
        add.setBorderPainted(false);
        add.setContentAreaFilled(false);
        add.setFocusable(false);
        add.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jToolBar1.add(add);
        jToolBar1.add(jSeparator1);

        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit.png"))); // NOI18N
        edit.setText("Editar");
        edit.setBorderPainted(false);
        edit.setContentAreaFilled(false);
        edit.setEnabled(false);
        edit.setFocusable(false);
        edit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        edit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jToolBar1.add(edit);

        borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete.png"))); // NOI18N
        borrar.setText("Borrar");
        borrar.setBorderPainted(false);
        borrar.setContentAreaFilled(false);
        borrar.setEnabled(false);
        borrar.setFocusable(false);
        borrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        borrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });
        jToolBar1.add(borrar);
        jToolBar1.add(jSeparator2);

        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/continue.png"))); // NOI18N
        guardar.setText("Guardar");
        guardar.setBorderPainted(false);
        guardar.setContentAreaFilled(false);
        guardar.setEnabled(false);
        guardar.setFocusable(false);
        guardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        guardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        jToolBar1.add(guardar);

        cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancel.png"))); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.setBorderPainted(false);
        cancelar.setContentAreaFilled(false);
        cancelar.setEnabled(false);
        cancelar.setFocusable(false);
        cancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        jToolBar1.add(cancelar);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        progreso.setFont(progreso.getFont().deriveFont(progreso.getFont().getSize()-2f));
        progreso.setText("Preparado.");
        progreso.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        getContentPane().add(progreso, java.awt.BorderLayout.PAGE_END);

        jPanel1.setLayout(new java.awt.BorderLayout());

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);
        jPanel1.add(detalle, java.awt.BorderLayout.LINE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        detalle.setProfesor(null);
        detalle.setEditable(true);
        detalle.loadData();
        guardar.setEnabled(true);
        cancelar.setEnabled(true);
    }//GEN-LAST:event_addActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        try {
            detalle.setProfesor(obtenerProfesor());
            detalle.setEditable(true);
            detalle.loadData();
            guardar.setEnabled(true);
            cancelar.setEnabled(true);
        } catch (DAOException ex) {
            Logger.getLogger(ListProfesoresFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        if (JOptionPane.showConfirmDialog(rootPane, "¿Seguro que quieres borrar este profesor?",
                "Borrar profesor", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
            try {
                Profesor aBorrar = obtenerProfesor();
                manager.getProfesorDAO().eliminar(aBorrar);
                actualizarTabla();
                tabla.clearSelection();
                edit.setEnabled(false);
                borrar.setEnabled(false);
                guardar.setEnabled(false);
                cancelar.setEnabled(false);
            } catch (DAOException ex) {
                Logger.getLogger(ListProfesoresFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_borrarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        detalle.setProfesor(null);
        detalle.setEditable(false);
        detalle.loadData();
        
        guardar.setEnabled(false);
        cancelar.setEnabled(false);
    }//GEN-LAST:event_cancelarActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        try {
            detalle.saveData();
            Profesor datosProfesor = detalle.getProfesor();
            if (datosProfesor.getId() == null) {
                manager.getProfesorDAO().insertar(datosProfesor);
            } else {
                manager.getProfesorDAO().modificar(datosProfesor);
            }
            actualizarTabla();
            detalle.setProfesor(null);
            detalle.setEditable(false);
            detalle.loadData();
            guardar.setEnabled(false);
            cancelar.setEnabled(false);
        } catch (DAOException ex) {
            Logger.getLogger(ListProfesoresFrame.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_guardarActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    MySQLDaoManager manager = new MySQLDaoManager("localhost", "ejemplo", "ejemplo", "escuela");
                    new ListProfesoresFrame(manager).setVisible(true);
                } catch (SQLException | DAOException ex) {
                    Logger.getLogger(ListProfesoresFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton borrar;
    private javax.swing.JButton cancelar;
    private es.makigas.escuela.frames.profesores.DetalleProfesorPanel detalle;
    private javax.swing.JButton edit;
    private javax.swing.JButton guardar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel progreso;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
